### ISSUE TITLE
versions after 4.3 are undocumented on Pursuit

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-quickcheck#83]
https://pursuit.purescript.org/packages/purescript-quickcheck/4.3.0

**Comment by kejace** [comment]
I wonder if this relates to

```
> pulp docs
* Generating documentation in ...
Error found:
in module Test.QuickCheck.Gen
at ./.psc-package/master/quickcheck/v4.6.0/src/Test/QuickCheck/Gen.purs line 79, column 16 - line 79, column 52

  No type class instance was found for

    Control.Monad.Rec.Class.MonadRec (State
                                        { newSeed :: Seed
                                        , size :: Int
                                        }
                                     )
```

**Comment by matthewleon** [comment]
@kejace Can't reproduce on my end. Strange. `purs` 0.11.7, MacOS.

**Comment by paf31** [comment]
I think someone just needs to upload them.

**Comment by XertroV** [comment]
I think there is actually a bug with `Test.QuickCheck.Gen` - or at least something funny.

I get the same error when generating docs locally (using `pulp docs`).

```
Error found:
in module Test.QuickCheck.Gen
at ./bower_components/purescript-quickcheck/src/Test/QuickCheck/Gen.purs line 79, column 16 - line 79, column 52

  No type class instance was found for

    Control.Monad.Rec.Class.MonadRec (State
                                        { newSeed :: Seed
                                        , size :: Int
                                        }
                                     )
```

Full error: https://gist.github.com/XertroV/5001704845eeba1075c1abfb7fb1fc86

Also 0.11.7 on MacOS (and 0.11.6 and 0.11.5 too - tested 0.11.0 but some stuff was broken with RowCons)

**Comment by garyb** [comment]
Ah yeah I fixed the pursuit upload yesterday.

@XertroV you might have outdated local dependencies. It builds fine on Travis / for me / in other places, so it points to something local anyway. :smile:

**Comment by XertroV** [comment]
@garyb thanks for the quick reply.

Any hints on how I should troubleshoot locally? Have tried `rm -rf bower_components` and then `bower install`. Also tried manually specifying quickcheck@4.6.1 -- still getting the same error. Next step is to try building on a linux box I have (using macos atm). To be clear - it builds fine and tests fine, it's just the docs :/

There are a number of libs I need to manually specify while installing still due to different dependencies (e.g. prelude v2.1.0 or v.2.5.0 or v.3.0.0 or v.3.1.0 (though they resolve to 2.5.0 and 3.1.1 respectively) - not sure if these could be doing something icky.

**Comment by hdgarrood** [comment]
> There are a number of libs I need to manually specify while installing still due to different dependencies (e.g. prelude v2.1.0 or v.2.5.0 or v.3.0.0 or v.3.1.0 (though they resolve to 2.5.0 and 3.1.1 respectively) - not sure if these could be doing something icky.

This is probably related to how things are going wrong. When I `rm -r bower_components && bower install` I don't have to manually specify any versions of dependencies. Maybe try `bower cache clean && rm -r bower_components && bower install`?

**Comment by hdgarrood** [comment]
Although, the fact that it builds and tests fine but you only get this error when trying to build docs makes me suspect that this might be a bug in the docs generation part of the compiler... Can you let me know which versions of `quickcheck`, `transformers`, and `tailrec` you're using when you get this error?

**Comment by XertroV** [comment]
Thanks @hdgarrood - trying now.

I feel like I should note I'm not compiling `purescript-quickcheck` when I've got that issue - it's something I'm working on at the moment with a bunch of dependencies. Feels like Haskell and cabal hell a bit :P 

Here's a sample of one of the worrying things when `bower install`ing:

```
Please note that,
    purescript-web3#0.10.0 depends on purescript-profunctor-lenses#v3.7.0 which resolved to purescript-profunctor-lenses#3.7.0
    basl depends on purescript-profunctor-lenses#^3.8.0 which resolved to purescript-profunctor-lenses#3.8.0
    purescript-ipfs-api#0.0.2 depends on purescript-profunctor-lenses#^3.6.0 which resolved to purescript-profunctor-lenses#3.8.0
    purescript-argonaut-traversals#3.1.0 depends on purescript-profunctor-lenses#^3.0.0 which resolved to purescript-profunctor-lenses#3.8.0
Resort to using purescript-profunctor-lenses#^3.8.0 which resolved to purescript-profunctor-lenses#3.8.0
Code incompatibilities may occur.
```
(`basl` is the thing I'm working on)

-----

going by the `.bower.json` files in `bower_components`:

* quickcheck: 4.6.1
* tailrec: 3.3.0
* transformers 3.4.0

**Comment by hdgarrood** [comment]
Hm, generating docs still works for me locally with `purs` v0.11.7 with those versions... what happens if you delete the `output` directory as well?

**Comment by XertroV** [comment]
@hdgarrood - Tried that unfortunately, and going fresh on a linux box - I think it must be something to do with my set of dependencies; the error message is so opaque though. Will try removing all the tests and seeing if that helps, maybe I can narrow it down a bit.

As an aside, I often run into two errors before that one, one each with purescript-aff-coroutine and purescript-aff-promise. I get type errors and if I change to the other of the two presented options they go away and I can compile again (but not generate docs). That's the main reason I think dependencies have something to do with it.

Will let you know if I dig anything up.
